name: Push on Master jobs

on:
  push:
    branches: [ master ]

jobs:
  automaticpublish:
    name: Automatic Mod Browser Publish Integration
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
       
      # Mod Browser integration
      - uses: JavidPack/tModLoaderPublishIntegration@v0.11.8.3
        with:
          STEAMID64: ${{secrets.76561199068151307}}
          MODBROWSERPASSPHRASE: ${{secrets.6b4306ba132027520dbcae373d51f7c5}}
          MODNAME: COD_zombies
